library(ape)

# Reading metadata for Senegal only samples and close global reference (CGR) samples
SN.data <- read.csv(system.file("data/HIV_subtypes_summary_SENEGAL_noDups.csv", package = "senegalHIVmodel"))
CGR.data <-  read.csv(system.file("data/HIV_subtypes_summary_CGR.csv", package = "senegalHIVmodel"))

all_data_list <- organize_metadata_bySubtype(SN.data, CGR.data, code = 2)

all_data_SN_CGR <- all_data_list$SN_df
all_data_missingSample <- all_data_list$missing_sample

# Drop rows in which sex or Risk Group is NA, or Risk Group = Children
all_data_SN_CGR.2 <- subset(all_data_SN_CGR, is.na(Risk_group) == FALSE & Risk_group != "Children" &
                              (is.na(Sex) & Risk_group != "CGR")  == FALSE)
all_data_SN_CGR.2["lower"] <- NA
all_data_SN_CGR.2["upper"] <- NA


all_data_missingSample.2 <- subset(all_data_missingSample, is.na(Risk_group) == FALSE & Risk_group != "Children" &
                                     (is.na(Sex) & Risk_group != "CGR")  == FALSE)

dec.na <- is.na(all_data_SN_CGR.2$decimal)
all_data_SN_CGR.2$lower[is.na(all_data_SN_CGR.2$decimal)] <- all_data_missingSample.2$lower[match(all_data_SN_CGR.2$tip[dec.na], all_data_missingSample.2$tip)]
all_data_SN_CGR.2$upper[is.na(all_data_SN_CGR.2$decimal)] <- all_data_missingSample.2$upper[match(all_data_SN_CGR.2$tip[dec.na], all_data_missingSample.2$tip)]

#### match tip name with tip name as beast and phydyn
# all_info object is generated by running script "prepare_data_for_beast.R"
all_data_SN_CGR.2["phydyn_tip"] <- all_info$phydyn_tip[match(all_data_SN_CGR.2$tip, all_info$tip)]


#### READ FASTA file with alignment #######
library(seqinr)
all.seq <- read.fasta(system.file("data/alignments/all_subtypes_phydyn_NAremoved.fasta", package = "senegalHIVmodel"))

names(all.seq)

all_data_SN_CGR.3 <- all_data_SN_CGR.2[order(match(all_data_SN_CGR.2$phydyn_tip, names(all.seq))), ]

write.nexus.data(all.seq, file="~/Desktop/teste.nexus", format="dna", interleaved = FALSE)

fileConn<-file("~/Desktop/teste.nexus", open="a")
writeLines("begin assumptions;", fileConn)
writeLines("\t charset partition1 = 1-1302\\3,2-1302\\3;", fileConn)
writeLines("\t charset partition2 = 3-1302\\3;", fileConn)
writeLines("end;", fileConn)
writeLines("\n", fileConn)

writeLines("begin assumptions;", fileConn)
writeLines("\t OPTIONS SCALE = years;", fileConn)
writeLines("\n", fileConn)


i=1
while(i < 517){
  if(i == 516){
    if(is.na(all_data_SN_CGR.3["decimal"][i,])){
      text.to.write <- paste("\t CALIBRATE", all_data_SN_CGR.3["phydyn_tip"][i,], "=",
                             paste("uniform(", as.character(all_data_SN_CGR.3["lower"][i,]), ", ",
                                   as.character(all_data_SN_CGR.3["upper"][i,]), ")", ";", sep = ""), sep = " ")
      writeLines(text.to.write, fileConn)

    }else{
      text.to.write <- paste("\t CALIBRATE", all_data_SN_CGR.3["phydyn_tip"][i,], "=",
                             paste("fixed(", as.character(all_data_SN_CGR.3["decimal"][i,]), ")", ";", sep = ""), sep = " ")
      writeLines(text.to.write, fileConn)
    }
  }else{
    if(is.na(all_data_SN_CGR.3["decimal"][i,])){
      text.to.write <- paste("\t CALIBRATE", all_data_SN_CGR.3["phydyn_tip"][i,], "=",
                             paste("uniform(", as.character(all_data_SN_CGR.3["lower"][i,]), ", ",
                                   as.character(all_data_SN_CGR.3["upper"][i,]), ")", ",", sep = ""), sep = " ")
      writeLines(text.to.write, fileConn)

    }else{
      text.to.write <- paste("\t CALIBRATE", all_data_SN_CGR.3["phydyn_tip"][i,], "=",
                             paste("fixed(", as.character(all_data_SN_CGR.3["decimal"][i,]), ")", ",", sep = ""), sep = " ")
      writeLines(text.to.write, fileConn)
    }
  }
  i = i + 1
}

writeLines("end;", fileConn)

close(fileConn)

## READ NEWICK TREE ###
all_tree <- read.tree(system.file("data/bindTree_CGR_GTR+Gp12+3_droppedTip.tre", package = "senegalHIVmodel"))
old <- all_tree$tip.label

all_tree$tip.label <- all_data_SN_CGR.2$phydyn_tip[match(all_tree$tip.label, all_data_SN_CGR.2$tip)]

write.tree(all_tree, "inst/data/bindTree_CGR_GTR+Gp12+3_droppedTip_phydynBeast.tre")
