# script used to run a Markov Chain Monte Carlo analysis to estimate the
# parameters of the HIV model
# It used the R package BayesianTools for the MCMC analysis
# It used the R package phydynR to calculate the likelihood

# laad the mathematical model
source("analysis/scripts/model.R")
#load the data that will be used in the subsequent analysis
source("analysis/scripts/load_data.R")

library(phydynR)
library(akima)
library(BayesianTools)


# Specify a density function to be used in the prior especification (see below)
densities <-  function(par){
  # d1 to d3 and d5 to d7 I am using a lognormal distribution with mean = R0 = 1.1 and sigma = 1
  # d4 and d8 uniform distribution between the start time and the most recent sample
  # d9 exponential distribution with mean around 1/30
  # d10 exponential distribution with mean around 1/20
  d1 = dgamma(par[1], shape = 3, rate = 3/1.1, log = TRUE) #gpsp0
  d2 = dgamma(par[2], shape = 3, rate = 3/1.1, log = TRUE) #gpsp1
  d3 = dgamma(par[3], shape = 3, rate = 3/1.1, log = TRUE) #gpsp2
  d4 = dunif(par[4], min = 1978, max = 2014, log = TRUE) #gpsploc
  d5 = dgamma(par[5], shape = 3, rate = 3/1.1, log = TRUE) #msmsp0
  d6 = dgamma(par[6], shape = 3, rate = 3/1.1, log = TRUE) #msmsp1
  d7 = dgamma(par[7], shape = 3, rate = 3/1.1, log = TRUE) #msmsp2
  d8 = dunif(par[8], min = 1978, max = 2014, log = TRUE) #msmsploc
  d9 = dexp(par[9], rate = 30, log = TRUE) #import
  d10 = dexp(par[10], rate = 20, log = TRUE) #srcNe
  d11 = dbeta(par[11], shape1 = 16, shape2 = 4, log = TRUE) #pmsm2msm
  d12 = dbeta(par[12], shape1 = 16, shape2 = 4, log = TRUE) #pgpf2gpm

  return(d1 + d2 + d3 + d4 + d5 + d6 + d7 + d8 + d9 + d10 + d11 + d12)
}


# Create sampling, this is optional but recommended because the MCMCs can generate automatic starting
# conditions if this is provided
sampler <-  function(n=1){
  d1 = rgamma(n, shape = 3, rate = 3/1.1) #gpsp0
  d2 = rgamma(n, shape = 3, rate = 3/1.1) #gpsp1
  d3 = rgamma(n, shape = 3, rate = 3/1.1) #gpsp2
  d4 = runif(n, min = 1978, max = 2014) #gpsploc
  d5 = rgamma(n, shape = 3, rate = 3/1.1) #msmsp0
  d6 = rgamma(n, shape = 3, rate = 3/1.1) #msmsp1
  d7 = rgamma(n, shape = 3, rate = 3/1.1) #msmsp2
  d8 = runif(n, min = 1978, max = 2014) #msmsploc
  d9 = rexp(n, rate = 30) #import
  d10 = rexp(n, rate = 20) #srcNe
  d11 = rbeta(n, shape1 = 16, shape2 = 4) #pmsm2msm
  d12 = rbeta(n, shape1 = 16, shape2 = 4) #pgpf2gpm

  return(cbind(d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12))
}

# Create prior (necessary for the BayesianTools package)
prior <- createPrior(density = densities, sampler = sampler, lower = c(0.01, 0.01, 0.01, 1978, 0.01, 0.01, 0.01, 1978, 0, 0.0001, 0.3, 0.3), upper = c(3, 3, 3, 2014, 3, 3, 3, 2014, 0.15, 0.15, 1, 1))

# Note that before proceding to reading a previous run, we first run several mcmc
# runs in order to get an ok run to create a z-matrix (for more details see Braak and Vrugt 2008)
# This run was generated by the following lines of commented code and ignoring everything else:
# bayesianSetup <- createBayesianSetup(likelihood = obj_fun , prior = prior)
# settings = list(iterations = 18000, nrChains = 1, thin = 1)
# out <- runMCMC(bayesianSetup = bayesianSetup, sampler = "DEzs", settings = settings)


# After we had a run to create a z-matrix we did the follow:
# Read a previous run for creating starting values for the Z matrix
runZ <- readRDS("data/outDEZs_37147513_0_18000_1.rds")

# Get a good sample (the run above is not good, however it can provide a good Z matrix)
# For more information on this: https://github.com/florianhartig/BayesianTools/issues/79
x <- getSample(runZ, start=3000)
# Get the range for the parameter estimates for the previous run
rangePost = apply(x, 2, range)

#get unique values of x
u_x <- unique(x)

#cretae new Z matrix based on previous run
newZ = matrix(runif(1500, rangePost[1,], rangePost[2,]), ncol = 12, byrow = T)

# Because I will run several analysis in parallel, and to avoid the initial values to be identical
# I will provide as argument position 1 (pos1), position 2 (pos2), and position 3 (pos3)
# from the unique values of x (u_x)
pos1=4
pos2=5
pos3=6
iter=18000 # number of iterations
settings = list(Z = newZ, startValue =  u_x[c(pos1, pos2, pos3), ], nrChains = 1, iterations = iter, thin = 1)

# Create bayesianSetup
bayesianSetup <- createBayesianSetup(likelihood = obj_fun , prior = prior)

out <- runMCMC(bayesianSetup = bayesianSetup,  sampler = "DEzs", settings = settings )

# save output file for later analysis, i.e. check convergence, plot samples, etc
# give the name that you wish, i.e. mcmc_run.RDS
saveRDS(out, "mcmc_run.RDS")
