---
title: "Percentage of infected"
author: "Fabrícia F. Nascimento"
date: "`r Sys.Date()`"
output:
  rmarkdown::pdf_document:
    fig_caption: true
    df_print: kable
    highlight: pygments
fontsize: 12pt
vignette: >
  %\VignetteIndexEntry{Percentage of infected}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "latex")
```

# Percentage of infected in 2014

Tables below show the median and credible interval for the percentage of 
infected in $gpm$, $gpf$, and $msm$ in 2014.

## All subtypes

### Model 2 and Model 5 (prevalence)

```{r echo = FALSE}
load("data_files/infections.rda")

#All subtypes combined
#Model 2 and Model 5 (prevalence)
m25 <- infections_All[infections_All$Model == "Model 2" | infections_All$Model == "Model 5", ]
m25["CI"] <- paste("(", round(m25$lower,2), "-", round(m25$upper,2), ")", sep="")
m25["proportions"] <- paste(round(m25$median,2), m25$CI, sep=" ")

m25mod <- m25[c("group", "Model", "proportions")]
m25_wide <- reshape2::dcast(m25mod, group ~ Model , value.var="proportions")




kable_table.m25 <- knitr::kable(m25_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.m25,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```

### Model 3 and Model 6 (prevalence) 

```{r echo = FALSE}

#All subtypes combined
#Model 3 and Model 6 (prevalence)
m36 <- infections_All[infections_All$Model == "Model 3" | infections_All$Model == "Model 6", ]
m36["CI"] <- paste("(", round(m36$lower,2), "-", round(m36$upper,2), ")", sep="")
m36["proportions"] <- paste(round(m36$median,2), m36$CI, sep=" ")

m36mod <- m36[c("group", "Model", "proportions")]
m36_wide <- reshape2::dcast(m36mod, group ~ Model , value.var="proportions")


kable_table.m36 <- knitr::kable(m36_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.m36,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```

### Model 4 and Model 7 (prevalence) 

```{r echo = FALSE}

#All subtypes combined
#Model 4 and Model 7 (prevalence)
m47 <- infections_All[infections_All$Model == "Model 4" | infections_All$Model == "Model 7", ]
m47["CI"] <- paste("(", round(m47$lower,2), "-", round(m47$upper,2), ")", sep="")
m47["proportions"] <- paste(round(m47$median,2), m47$CI, sep=" ")

m47mod <- m47[c("group", "Model", "proportions")]
m47_wide <- reshape2::dcast(m47mod, group ~ Model , value.var="proportions")


kable_table.m47 <- knitr::kable(m47_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.m47,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```

### Subtype C

```{r echo = FALSE}

#Subtype C
infections_C["CI"] <- paste("(", round(infections_C$lower,2), "-", round(infections_C$upper,2), ")", sep="")
infections_C["proportions"] <- paste(round(infections_C$median,2), infections_C$CI, sep=" ")

mC <- infections_C[c("group", "Model", "proportions")]
mC_wide <- reshape2::dcast(mC, group ~ Model , value.var="proportions")


kable_table.mC <- knitr::kable(mC_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.mC,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```


### Subtype 02_AG

```{r echo = FALSE}

#Subtype 02_AG
infections_AG["CI"] <- paste("(", round(infections_AG$lower,2), "-", round(infections_AG$upper,2), ")", sep="")
infections_AG["proportions"] <- paste(round(infections_AG$median,2), infections_AG$CI, sep=" ")

mAG <- infections_AG[c("group", "Model", "proportions")]
mAG_wide <- reshape2::dcast(mAG, group ~ Model , value.var="proportions")


kable_table.mAG <- knitr::kable(mAG_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.mAG,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```
