---
title: "MAP and ESS for main models showed in paper"
author: "Fabrícia F. Nascimento"
date: "`r Sys.Date()`"
output:
  rmarkdown::pdf_document:
    fig_caption: true
    df_print: kable
    highlight: pygments
fontsize: 12pt
vignette: >
  %\VignetteIndexEntry{MAP and ESS for main models showed in paper}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "latex")
```

```{r echo = FALSE}
load(system.file("data/mcmc_runs/AG_m4.rda",
                  package = "senegalHIVmodel"))
load(system.file("data/mcmc_runs/C_m4.rda",
                  package = "senegalHIVmodel"))
load(system.file("data/mcmc_runs/Model6.rda",
                  package = "senegalHIVmodel"))


# Get ESS for each parameter
Cm4.s <- BayesianTools::getSample(C_m4.2, start = 1200, coda = TRUE)
Cm4.IQR <- as.data.frame(summary(Cm4.s)$quantiles[,c(3, 1, 5)])
Cm4.IQR <- format(round(Cm4.IQR, 2), nsmall = 2)
Cm4.IQR <- cbind("par_names" = c("gpsp0", "gpsp1", "gpsp2", "gpsploc", 
                     "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                     "maleX", "import", "srcNe",
                     "pmsm2msm", "pgpf2gpm",
                     "initmsm", "initgp"), Cm4.IQR)
# create dataframe to show table in paper
# estimates = median and credible interval
Cm4.IQR["Subtype C"] <- paste(paste(Cm4.IQR$`50%`, "", sep = " "), "(", Cm4.IQR$`2.5%`, " -- ", Cm4.IQR$`97.5%`,")", sep="")



# Subtype 02_AG model 4
AGm4.s <- BayesianTools::getSample(AG_m4.2, start = 1000, coda = TRUE)
AGm4.IQR <- as.data.frame(summary(AGm4.s)$quantiles[,c(3, 1, 5)])
AGm4.IQR <- format(round(AGm4.IQR, 2), nsmall = 2)
AGm4.IQR <- cbind("par_names" = c("gpsp0", "gpsp1", "gpsp2", "gpsploc", 
                     "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                     "maleX", "import", "srcNe",
                     "pmsm2msm", "pgpf2gpm",
                     "initmsm", "initgp"), AGm4.IQR)
# create dataframe to show table in paper
# estimates = median and credible interval
AGm4.IQR["Subtype 02_AG"] <- paste(paste(AGm4.IQR$`50%`, "", sep = " "), "(", AGm4.IQR$`2.5%`, " -- ", AGm4.IQR$`97.5%`,")", sep="")


# Model 6 (subytypes combined)
m6.s <- BayesianTools::getSample(m6.1, start = 1200, coda = TRUE)
m6.IQR <- as.data.frame(summary(m6.s)$quantiles[,c(3, 1, 5)])
m6.IQR <- format(round(m6.IQR, 2), nsmall = 2)
m6.IQR <- cbind("par_names" = c("gpsp0", "gpsp1", "gpsp2", "gpsploc", 
                     "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                     "maleX", "import", "srcNe",
                     "pmsm2msm", "pgpf2gpm",
                     "initmsm", "initgp"), m6.IQR)
# create dataframe to show table in paper
# estimates = median and credible interval
m6.IQR["Subtypes combined"] <- paste(paste(m6.IQR$`50%`, "", sep = " "), "(", m6.IQR$`2.5%`, " -- ", m6.IQR$`97.5%`,")", sep="")


# merge dataframes
all_models = cbind(Cm4.IQR[c(1,5)], AGm4.IQR[5], m6.IQR[c(5)]) 
rownames(all_models) <- NULL
all_models <- as.matrix(all_models)

kable_table_all <- knitr::kable(all_models, booktabs = TRUE, 
                                caption = "Estimates (median and credible interval) 
                                for parameters of mathematical model describing
                                transmissions")
kableExtra::kable_styling(kable_input = kable_table_all,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")
```
