---
title: "Preliminary results"
author: "Fabricia F. Nascimento"
date: "`r Sys.Date()`"
output:
  rmarkdown::pdf_document:
    fig_caption: true
    df_print: kable
    highlight: pygments
fontsize: 12pt
vignette: >
  %\VignetteIndexEntry{Preliminary results}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "latex")
```



```{r echo = FALSE}
load(system.file("data/mcmc_runs/mergedRuns_model5_mx.rda",
                                    package = "senegalHIVmodel"))
load(system.file("data/mcmc_runs/mergedRuns_model7_mx.rda",
                                    package = "senegalHIVmodel"))
load(system.file("data/mcmc_runs/mergedRuns_subtype_prevalence.rda",
                                    package = "senegalHIVmodel"))

# MAP after removing first 1,000 iterations
model5.mx <- BayesianTools::MAP(m5.m, start=1000)
model5.mx.p <- as.numeric(format(round(model5.mx$parametersMAP, 3), nsmall = 3))
model5.mx.p[[16]] <- model5.mx$valuesMAP[[1]]
names(model5.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                         "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                         "maleX", "import", "srcNe",
                         "pmsm2msm", "pgpf2gpm",
                         "initmsm", "initgp", "Lposterior"))
# MAP after removing first 1,000 iterations
model7.mx <- BayesianTools::MAP(m7.m, start=1000)
model7.mx.p <- as.numeric(format(round(model7.mx$parametersMAP, 3), nsmall = 3))
model7.mx.p[[16]] <- model7.mx$valuesMAP[[1]]
names(model7.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                         "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                         "maleX", "import", "srcNe",
                         "pmsm2msm", "pgpf2gpm",
                         "initmsm", "initgp", "Lposterior"))

# MAP after removing first 1,000 iter
m02_AG_m3.mx <- BayesianTools::MAP(m02_AG_m3, start=1000)
m02_AG_m3.mx.p <- as.numeric(format(round(m02_AG_m3.mx$parametersMAP, 3), nsmall = 3))
m02_AG_m3.mx.p[[16]] <- m02_AG_m3.mx$valuesMAP[[1]]
names(m02_AG_m3.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                            "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                            "maleX", "import", "srcNe",
                            "pmsm2msm", "pgpf2gpm",
                            "initmsm", "initgp", "Lposterior"))
# MAP after removing first 1,000 iter
m02_AG_m4.mx <- BayesianTools::MAP(m02_AG_m4, start=1000)
m02_AG_m4.mx.p <- as.numeric(format(round(m02_AG_m4.mx$parametersMAP, 3), nsmall = 3))
m02_AG_m4.mx.p[[16]] <- m02_AG_m4.mx$valuesMAP[[1]]
names(m02_AG_m4.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                            "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                            "maleX", "import", "srcNe",
                            "pmsm2msm", "pgpf2gpm",
                            "initmsm", "initgp", "Lposterior"))
# MAP after removing 800 iterations
mC_m3.mx <- BayesianTools::MAP(mC_m3, start=800)
mC_m3.mx.p <- as.numeric(format(round(mC_m3.mx$parametersMAP, 3), nsmall = 3))
mC_m3.mx.p[[16]] <- mC_m3.mx$valuesMAP[[1]]
names(mC_m3.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                        "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                        "maleX", "import", "srcNe",
                        "pmsm2msm", "pgpf2gpm",
                        "initmsm", "initgp", "Lposterior"))
#MAP for model 4 subtype C
mC_m4.mx <- BayesianTools::MAP(mC_m4, start=1000)
mC_m4.mx.p <- as.numeric(format(round(mC_m4.mx$parametersMAP, 3), nsmall = 3))
mC_m4.mx.p[[16]] <- mC_m4.mx$valuesMAP[[1]]
names(mC_m4.mx.p) <- (c("gpsp0", "gpsp1", "gpsp2", "gpsploc",
                    "msmsp0", "msmsp1", "msmsp2", "msmsploc",
                    "maleX", "import", "srcNe",
                    "pmsm2msm", "pgpf2gpm",
                    "initmsm", "initgp", "Lposterior"))



data_list.mx = data.frame(model5.mx.p, model7.mx.p, m02_AG_m3.mx.p, m02_AG_m4.mx.p, mC_m3.mx.p, mC_m4.mx.p) 
data_list.mx <- as.matrix(data_list.mx)
colnames(data_list.mx)<-c("M5","M7", "02_AG: m3", "02_AG: m4", "C: m3", "C: m4")

kable_table.mx <- knitr::kable(data_list.mx, booktabs = T, caption =  "MAP for preliminary MCMC runs: 15 parameters with prevalence")
kableExtra::kable_styling(kable_input = kable_table.mx,
                          latex_options = c("striped", "scale_down", "hold_position"),
                          full_width = FALSE, position = "center")

```

# Line Plots: 15 parameters including prevalence
```{r echo = FALSE}
library(reshape2)
library(ggplot2)
# create dataframe to make plots
MAP_models.mx <- data.frame(model5.mx.p, model7.mx.p, m02_AG_m3.mx.p, m02_AG_m4.mx.p, mC_m3.mx.p, mC_m4.mx.p)

MAP_models_t.mx <- data.frame(t(MAP_models.mx[-16,]))
MAP_models_t.mx["model"] <- rownames(MAP_models_t.mx)

MAP_models_long.mx <- melt(MAP_models_t.mx, id.vars="model")


#plots
gpsp_values.mx <- MAP_models_long.mx[c(1:18),]
gpsp_values.mx$model <- as.factor(gpsp_values.mx$model)

ggplot(data=gpsp_values.mx, aes(x=variable, y=value, group=model, shape=model, colour=model)) +
  geom_line(aes(linetype=model), size=0.5) +     # Set linetype by sex
  geom_point(size=2, fill="white") +         # Use larger points, fill with white
  expand_limits(y=0) +                       # Set y range to include 0
  scale_colour_hue(name="Model",      # Set legend title
                   l=30)  +                  # Use darker colors (lightness=30)
  scale_shape_manual(name="Model",
                     values=c(0, 15, 1, 16, 2, 18)) +      # Use points with a fill color
  scale_linetype_discrete(name="Model") +
  xlab("parameter") + ylab("value") + # Set axis labels
  theme_bw() + ggtitle("Shape parameter for gp") +
  theme(legend.position=c(.7, .7))           # Position legend inside
# This must go after theme_bw

```

```{r echo = FALSE}
msmsp_values.mx <- MAP_models_long.mx[c(25:42),]
msmsp_values.mx$model <- as.factor(msmsp_values.mx$model)

ggplot(data=msmsp_values.mx, aes(x=variable, y=value, group=model, shape=model, colour=model)) +
  geom_line(aes(linetype=model), size=0.5) +     # Set linetype by sex
  geom_point(size=2, fill="white") +         # Use larger points, fill with white
  expand_limits(y=0) +                       # Set y range to include 0
  scale_colour_hue(name="Model",      # Set legend title
                   l=30)  +                  # Use darker colors (lightness=30)
  scale_shape_manual(name="Model",
                     values=c(0, 15, 1, 16, 2, 18)) +      # Use points with a fill color
  scale_linetype_discrete(name="Model") +
  xlab("parameter") + ylab("value") + # Set axis labels
  theme_bw() + ggtitle("Shape parameter for msm") +
  theme(legend.position=c(.86, .7))           # Position legend inside
# This must go after theme_bw

```
