---
title: "Tables showed in the paper"
author: "Fabrícia F. Nascimento"
date: "`r Sys.Date()`"
output:
  rmarkdown::pdf_document:
    fig_caption: true
    df_print: kable
    highlight: pygments
fontsize: 12pt
vignette: >
  %\VignetteIndexEntry{Tables showed in the paper}
  %\VignetteEngine{rmarkdown::render}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "latex")
```

```{r echo = FALSE}
# script to create table for the proportion of the effective number of infections
# in 2014 for models that we show in the main paper

################################################################################
# proportion of effective number of infections for 2014
load("data_files/infections.rda")

# proportions of gpf, gpm and msm for Model 4 and subtype C
C_gpf.p <- subset(infections_C, group == "gpf" & Model == "Model 4")
C_gpf.p["CI"] <- paste("(", format(round(C_gpf.p$lower, 2), nsmall = 2), "-", 
                       format(round(C_gpf.p$upper,2), nsmall = 2), ")", sep="")
C_gpf.p["prop"] <- paste(format(round(C_gpf.p$median,2), nsmall = 2),
                         C_gpf.p$CI, sep=" ")

# separate the columns of interest in a different dataframe
C_gpf.p.df <- C_gpf.p[c("group", "prop")]
C_gpf.p.df["Model"] <- "Subtype C"
C_gpf.p.df["Variable"] <- "x"

C_gpm.p <- subset(infections_C, group == "gpm" & Model == "Model 4")
C_gpm.p["CI"] <- paste("(", format(round(C_gpm.p$lower, 2), nsmall = 2), "-", 
                       format(round(C_gpm.p$upper,2), nsmall = 2), ")", sep="")
C_gpm.p["prop"] <- paste(format(round(C_gpm.p$median,2), nsmall = 2),
                         C_gpm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
C_gpm.p.df <- C_gpm.p[c("group", "prop")]
C_gpm.p.df["Model"] <- "Subtype C"
C_gpm.p.df["Variable"] <- "y"

C_msm.p <- subset(infections_C, group == "msm" & Model == "Model 4")
C_msm.p["CI"] <- paste("(", format(round(C_msm.p$lower, 2), nsmall = 2), "-", 
                       format(round(C_msm.p$upper,2), nsmall = 2), ")", sep="")
C_msm.p["prop"] <- paste(format(round(C_msm.p$median,2), nsmall = 2),
                         C_msm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
C_msm.p.df <- C_msm.p[c("group", "prop")]
C_msm.p.df["Model"] <- "Subtype C"
C_msm.p.df["Variable"] <- "z"


# proportions of gpf, gpm and msm for Model 4 and subtype 02_AG
AG_gpf.p <- subset(infections_AG, group == "gpf" & Model == "Model 4")
AG_gpf.p["CI"] <- paste("(", format(round(AG_gpf.p$lower, 2), nsmall = 2), "-", 
                       format(round(AG_gpf.p$upper,2), nsmall = 2), ")", sep="")
AG_gpf.p["prop"] <- paste(format(round(AG_gpf.p$median,2), nsmall = 2),
                         AG_gpf.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
AG_gpf.p.df <- AG_gpf.p[c("group", "prop")]
AG_gpf.p.df["Model"] <- "Subtype 02_AG"
AG_gpf.p.df["Variable"] <- "x"


AG_gpm.p <- subset(infections_AG, group == "gpm" & Model == "Model 4")
AG_gpm.p["CI"] <- paste("(", format(round(AG_gpm.p$lower, 2), nsmall = 2), "-", 
                       format(round(AG_gpm.p$upper,2), nsmall = 2), ")", sep="")
AG_gpm.p["prop"] <- paste(format(round(AG_gpm.p$median,2), nsmall = 2),
                         AG_gpm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
AG_gpm.p.df <- AG_gpm.p[c("group", "prop")]
AG_gpm.p.df["Model"] <- "Subtype 02_AG"
AG_gpm.p.df["Variable"] <- "y"

AG_msm.p <- subset(infections_AG, group == "msm" & Model == "Model 4")
AG_msm.p["CI"] <- paste("(", format(round(AG_msm.p$lower, 4), nsmall = 2), "-", 
                       format(round(AG_msm.p$upper,4), nsmall = 2), ")", sep="")
AG_msm.p["prop"] <- paste(format(round(AG_msm.p$median,4), nsmall = 2),
                         AG_msm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
AG_msm.p.df <- AG_msm.p[c("group", "prop")]
AG_msm.p.df["Model"] <- "Subtype 02_AG"
AG_msm.p.df["Variable"] <- "z"

# proportions of gpf, gpm and msm for Model 6 and combined analyses (all subtypes)
gpf.p <- subset(infections_All, group == "gpf" & Model == "Model 6")
gpf.p["CI"] <- paste("(", format(round(gpf.p$lower, 2), nsmall = 2), "-", 
                       format(round(gpf.p$upper,2), nsmall = 2), ")", sep="")
gpf.p["prop"] <- paste(format(round(gpf.p$median,2), nsmall = 2),
                         gpf.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
gpf.p.df <- gpf.p[c("group", "prop")]
gpf.p.df["Model"] <- "Subtypes combined"
gpf.p.df["Variable"] <- "x"


gpm.p <- subset(infections_All, group == "gpm" & Model == "Model 6")
gpm.p["CI"] <- paste("(", format(round(gpm.p$lower, 2), nsmall = 2), "-", 
                       format(round(gpm.p$upper,2), nsmall = 2), ")", sep="")
gpm.p["prop"] <- paste(format(round(gpm.p$median,2), nsmall = 2),
                         gpm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
gpm.p.df <- gpm.p[c("group", "prop")]
gpm.p.df["Model"] <- "Subtypes combined"
gpm.p.df["Variable"] <- "y"


msm.p <- subset(infections_All, group == "msm" & Model == "Model 6")
msm.p["CI"] <- paste("(", format(round(msm.p$lower, 2), nsmall = 2), "-", 
                       format(round(msm.p$upper,2), nsmall = 2), ")", sep="")
msm.p["prop"] <- paste(format(round(msm.p$median,2), nsmall = 2),
                         msm.p$CI, sep=" ")
# separate the columns of interest in a different dataframe
msm.p.df <- msm.p[c("group", "prop")]
msm.p.df["Model"] <- "Subtypes combined"
msm.p.df["Variable"] <- "z"

################################################################################
# population attributable fraction (PAF) for 2014
load("data_files/PAF_2014.rda")

# PAF for gpf, gpm and msm for Model4 and subtype C
pafC_gpf <- subset(PAF_2014_C, group == "gpf" & Model == "Model 4")
pafC_gpf["CI"] <- paste("(", format(round(pafC_gpf$lower, 2), nsmall = 2), "-", 
                       format(round(pafC_gpf$upper,2), nsmall = 2), ")", sep="")
pafC_gpf["prop"] <- paste(format(round(pafC_gpf$median,2), nsmall = 2),
                         pafC_gpf$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafC_gpf.df <- pafC_gpf[c("group", "prop")]
pafC_gpf.df["Model"] <- "Subtype C"
pafC_gpf.df["Variable"] <- "PAF (gpf)"


pafC_gpm <- subset(PAF_2014_C, group == "gpm" & Model == "Model 4")
pafC_gpm["CI"] <- paste("(", format(round(pafC_gpm$lower, 2), nsmall = 2), "-", 
                       format(round(pafC_gpm$upper,2), nsmall = 2), ")", sep="")
pafC_gpm["prop"] <- paste(format(round(pafC_gpm$median,2), nsmall = 2),
                         pafC_gpm$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafC_gpm.df <- pafC_gpm[c("group", "prop")]
pafC_gpm.df["Model"] <- "Subtype C"
pafC_gpm.df["Variable"] <- "PAF (gpm)"

pafC_msm <- subset(PAF_2014_C, group == "msm" & Model == "Model 4")
pafC_msm["CI"] <- paste("(", format(round(pafC_msm$lower, 2), nsmall = 2), "-", 
                       format(round(pafC_msm$upper,2), nsmall = 2), ")", sep="")
pafC_msm["prop"] <- paste(format(round(pafC_msm$median,2), nsmall = 2),
                         pafC_msm$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafC_msm.df <- pafC_msm[c("group", "prop")]
pafC_msm.df["Model"] <- "Subtype C"
pafC_msm.df["Variable"] <- "PAF (msm)"

# PAF for gpf, gpm and msm for Model 4 and subtype 02_AG
pafAG_gpf <- subset(PAF_2014_AG, group == "gpf" & Model == "Model 4")
pafAG_gpf["CI"] <- paste("(", format(round(pafAG_gpf$lower, 2), nsmall = 2), "-", 
                       format(round(pafAG_gpf$upper,2), nsmall = 2), ")", sep="")
pafAG_gpf["prop"] <- paste(format(round(pafAG_gpf$median,2), nsmall = 2),
                         pafAG_gpf$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafAG_gpf.df <- pafAG_gpf[c("group", "prop")]
pafAG_gpf.df["Model"] <- "Subtype 02_AG"
pafAG_gpf.df["Variable"] <- "PAF (gpf)"


pafAG_gpm <- subset(PAF_2014_AG, group == "gpm" & Model == "Model 4")
pafAG_gpm["CI"] <- paste("(", format(round(pafAG_gpm$lower, 2), nsmall = 2), "-", 
                       format(round(pafAG_gpm$upper,2), nsmall = 2), ")", sep="")
pafAG_gpm["prop"] <- paste(format(round(pafAG_gpm$median,2), nsmall = 2),
                         pafAG_gpm$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafAG_gpm.df <- pafAG_gpm[c("group", "prop")]
pafAG_gpm.df["Model"] <- "Subtype 02_AG"
pafAG_gpm.df["Variable"] <- "PAF (gpm)"


pafAG_msm <- subset(PAF_2014_AG, group == "msm" & Model == "Model 4")
pafAG_msm["CI"] <- paste("(", format(round(pafAG_msm$lower, 5), nsmall = 2), "-", 
                       format(round(pafAG_msm$upper,4), nsmall = 2), ")", sep="")
pafAG_msm["prop"] <- paste(format(round(pafAG_msm$median,4), nsmall = 2),
                         pafAG_msm$CI, sep=" ")
# separate the columns of interest in a different dataframe
pafAG_msm.df <- pafAG_msm[c("group", "prop")]
pafAG_msm.df["Model"] <- "Subtype 02_AG"
pafAG_msm.df["Variable"] <- "PAF (msm)"

# PAF for gpf, gpm and msm for Model 6 and combined analyses (all subtypes)
paf_gpf <- subset(PAF_2014_combined, group == "gpf" & Model == "Model 6")
paf_gpf["CI"] <- paste("(", format(round(paf_gpf$lower, 2), nsmall = 2), "-", 
                       format(round(paf_gpf$upper,2), nsmall = 2), ")", sep="")
paf_gpf["prop"] <- paste(format(round(paf_gpf$median,2), nsmall = 2),
                         paf_gpf$CI, sep=" ")
# separate the columns of interest in a different dataframe
paf_gpf.df <- paf_gpf[c("group", "prop")]
paf_gpf.df["Model"] <- "Subtypes combined"
paf_gpf.df["Variable"] <- "PAF (gpf)"


paf_gpm <- subset(PAF_2014_combined, group == "gpm" & Model == "Model 6")
paf_gpm["CI"] <- paste("(", format(round(paf_gpm$lower, 2), nsmall = 2), "-", 
                       format(round(paf_gpm$upper,2), nsmall = 2), ")", sep="")
paf_gpm["prop"] <- paste(format(round(paf_gpm$median,2), nsmall = 2),
                         paf_gpm$CI, sep=" ")
# separate the columns of interest in a different dataframe
paf_gpm.df <- paf_gpm[c("group", "prop")]
paf_gpm.df["Model"] <- "Subtypes combined"
paf_gpm.df["Variable"] <- "PAF (gpm)"

paf_msm <- subset(PAF_2014_combined, group == "msm" & Model == "Model 6")
paf_msm["CI"] <- paste("(", format(round(paf_msm$lower, 2), nsmall = 2), "-", 
                       format(round(paf_msm$upper,2), nsmall = 2), ")", sep="")
paf_msm["prop"] <- paste(format(round(paf_msm$median,2), nsmall = 2),
                         paf_msm$CI, sep=" ")
# separate the columns of interest in a different dataframe
paf_msm.df <- paf_msm[c("group", "prop")]
paf_msm.df["Model"] <- "Subtypes combined"
paf_msm.df["Variable"] <- "PAF (msm)"


################################################################################
# Reproduction number (R0) for 2014

load("data_files/reproduction_number_2014.rda")

# R0 for gp, and msm for Model4 and subtype C
r0C_gp <- subset(r0_C_2014, group == "gp" & Model == "Model 4")
r0C_gp["CI"] <- paste("(", format(round(r0C_gp$lower, 2), nsmall = 2), "-", 
                       format(round(r0C_gp$upper,2), nsmall = 2), ")", sep="")
r0C_gp["prop"] <- paste(format(round(r0C_gp$median,2), nsmall = 2),
                         r0C_gp$CI, sep=" ")
# separate the columns of interest in a different dataframe
r0C_gp.df <- r0C_gp[c("group", "prop")]
r0C_gp.df["Model"] <- "Subtype C"
r0C_gp.df["Variable"] <- "R0 (gp)"


r0C_msm <- subset(r0_C_2014, group == "msm" & Model == "Model 4")
r0C_msm["CI"] <- paste("(", format(round(r0C_msm$lower, 2), nsmall = 2), "-", 
                       format(round(r0C_msm$upper,2), nsmall = 2), ")", sep="")
r0C_msm["prop"] <- paste(format(round(r0C_msm$median,2), nsmall = 2),
                         r0C_msm$CI, sep=" ")
# separate the columns of interest in a different dataframe
r0C_msm.df <- r0C_msm[c("group", "prop")]
r0C_msm.df["Model"] <- "Subtype C"
r0C_msm.df["Variable"] <- "R0 (msm)"

# R0 for gp, and msm for Model4 and subtype 02_AG
r0AG_gp <- subset(r0_AG_2014, group == "gp" & Model == "Model 4")
r0AG_gp["CI"] <- paste("(", format(round(r0AG_gp$lower, 2), nsmall = 2), "-", 
                       format(round(r0AG_gp$upper,2), nsmall = 2), ")", sep="")
r0AG_gp["prop"] <- paste(format(round(r0AG_gp$median,2), nsmall = 2),
                         r0AG_gp$CI, sep=" ")
# separate the columns of interest in a different dataframe
r0AG_gp.df <- r0AG_gp[c("group", "prop")]
r0AG_gp.df["Model"] <- "Subtype 02_AG"
r0AG_gp.df["Variable"] <- "R0 (gp)"

r0AG_msm <- subset(r0_AG_2014, group == "msm" & Model == "Model 4")
r0AG_msm["CI"] <- paste("(", format(round(r0AG_msm$lower, 2), nsmall = 2), "-", 
                       format(round(r0AG_msm$upper,2), nsmall = 2), ")", sep="")
r0AG_msm["prop"] <- paste(format(round(r0AG_msm$median,2), nsmall = 2),
                         r0AG_msm$CI, sep=" ")
# separate the columns of interest in a different dataframe
r0AG_msm.df <- r0AG_msm[c("group", "prop")]
r0AG_msm.df["Model"] <- "Subtype 02_AG"
r0AG_msm.df["Variable"] <- "R0 (msm)"

# R0 for gp, and msm for Model6 and combined analyses (all subtypes)
r0_gp <- subset(r0_combined_2014, group == "gp" & Model == "Model 6")
r0_gp["CI"] <- paste("(", format(round(r0_gp$lower, 2), nsmall = 2), "-", 
                       format(round(r0_gp$upper,2), nsmall = 2), ")", sep="")
r0_gp["prop"] <- paste(format(round(r0_gp$median,2), nsmall = 2),
                         r0_gp$CI, sep=" ")
# separate the columns of interest in a different dataframe
r0_gp.df <- r0_gp[c("group", "prop")]
r0_gp.df["Model"] <- "Subtypes combined"
r0_gp.df["Variable"] <- "R0 (gp)"

r0_msm <- subset(r0_combined_2014, group == "msm" & Model == "Model 6")
r0_msm["CI"] <- paste("(", format(round(r0_msm$lower, 2), nsmall = 2), "-", 
                       format(round(r0_msm$upper,2), nsmall = 2), ")", sep="")
r0_msm["prop"] <- paste(format(round(r0_msm$median,2), nsmall = 2),
                         r0_msm$CI, sep=" ")
r0_msm.df <- r0_msm[c("group", "prop")]
r0_msm.df["Model"] <- "Subtypes combined"
r0_msm.df["Variable"] <- "R0 (msm)"

all_data <- rbind(C_gpf.p.df, C_gpm.p.df, C_msm.p.df, AG_gpf.p.df, AG_gpm.p.df, AG_msm.p.df, gpf.p.df, gpm.p.df, msm.p.df, pafC_gpf.df, pafC_gpm.df, pafC_msm.df, pafAG_gpf.df, pafAG_gpm.df, pafAG_msm.df, paf_gpf.df, paf_gpm.df, paf_msm.df, r0C_gp.df, r0C_msm.df, r0AG_gp.df, r0AG_msm.df, r0_gp.df, r0_msm.df) 

all_data_wide <- reshape2::dcast(all_data, Variable ~ Model , value.var="prop")


kable_table.all <- knitr::kable(all_data_wide, booktabs = TRUE)
kableExtra::kable_styling(kable_input = kable_table.all,
                          latex_options = "striped",
                          full_width = FALSE, position = "center")

```
